package io.github.vlovric.kindleparser;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.github.vlovric.kindleparser.models.Clipping;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

public class FyodorClippingsParser {

    private final Path clippingsPath;
    private final String fyodorBin;
    private final ObjectMapper mapper;

    /**
     * Initializes the parser with the path to the MyClippings.txt file.
     * Looks for the FYODOR_BIN environment variable to locate the executable,
     * defaulting to "fyodor" otherwise. Configure Jackson to ignore unknown properties.
     *
     * @param clippingsPath the path to the Kindle clippings text file
     */
    public FyodorClippingsParser(Path clippingsPath) {
        this.clippingsPath = clippingsPath;
        String envBin = System.getenv("FYODOR_BIN");
        this.fyodorBin = (envBin != null && !envBin.isBlank()) ? envBin : "fyodor";
        
        this.mapper = new ObjectMapper()
                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    }

    /**
     * Executes the fyodor subprocess, captures its JSON output, deserializes it into
     * Clipping records, and applies a title filter. The returned list is sorted by location.
     *
     * @param titleFilter an optional substring to filter clippings by book title (case-insensitive)
     * @return a sorted list of Clipping records
     * @throws IOException          if temporary directories cannot be created or process I/O fails
     * @throws InterruptedException if the fyodor subprocess is interrupted
     */
    public List<Clipping> parse(String titleFilter) throws IOException, InterruptedException {
        Path tmpDir = Files.createTempDirectory("fyodor_");
        try {
            Path outputDir = tmpDir.resolve("out");
            Files.createDirectories(outputDir);

            setupFyodorConfig(tmpDir);

            ProcessBuilder pb = new ProcessBuilder(
                    fyodorBin,
                    clippingsPath.toAbsolutePath().toString(),
                    outputDir.toAbsolutePath().toString()
            );

            // Tell Fyodor to use our temporary directory as XDG_CONFIG_HOME
            // so it loads the custom config file pointing to our ERB template.
            Map<String, String> env = pb.environment();
            env.put("XDG_CONFIG_HOME", tmpDir.toAbsolutePath().toString());

            pb.redirectErrorStream(true);
            Process process = pb.start();
            int exitCode = process.waitFor();

            if (exitCode != 0) {
                String output = new String(process.getInputStream().readAllBytes());
                throw new IOException("Fyodor process failed with exit code " + exitCode + ": " + output);
            }

            List<Clipping> clippings = parseOutput(outputDir, titleFilter);
            
            // Sort by location safely (handling null locations)
            clippings.sort(Comparator.comparingInt(c -> c.location() == null ? 0 : c.location()));
            
            return clippings;

        } finally {
            deleteTempDir(tmpDir);
        }
    }

    /**
     * Prepares the temporary directory structure required by Fyodor.
     * Extracts the embedded ERB template from the JAR resources and creates
     * a minimal fyodor.toml config file pointing to it.
     *
     * @param tmpDir the temporary directory created for this execution run
     * @throws IOException if the resource is missing or disk writing fails
     */
    private void setupFyodorConfig(Path tmpDir) throws IOException {
        Path configDir = tmpDir.resolve("fyodor");
        Files.createDirectories(configDir);

        Path templatePath = configDir.resolve("template.erb");
        try (InputStream is = getClass().getResourceAsStream("/kindle_headings.erb")) {
            if (is == null) {
                throw new IOException("Could not find /kindle_headings.erb in resources");
            }
            Files.copy(is, templatePath, StandardCopyOption.REPLACE_EXISTING);
        }

        // Write the fyodor.toml config file
        Path configPath = configDir.resolve("fyodor.toml");
        String toml = "[output]\ntemplate = \"" + templatePath.toAbsolutePath().toString().replace("\\", "\\\\") + "\"\n";
        Files.writeString(configPath, toml);
    }

    /**
     * Reads all output files generated by Fyodor line by line.
     * Each line is parsed from JSON into a Clipping record and filtered
     * against the requested book title.
     *
     * @param outputDir   the directory containing Fyodor's generated output files
     * @param titleFilter the optional substring to compare against parsed book titles
     * @return a list of deserialized and filtered Clipping objects
     * @throws IOException if the output files cannot be read
     */
    private List<Clipping> parseOutput(Path outputDir, String titleFilter) throws IOException {
        List<Clipping> clippings = new ArrayList<>();
        
        try (Stream<Path> files = Files.list(outputDir)) {
            for (Path file : (Iterable<Path>) files::iterator) {
                if (Files.isRegularFile(file)) {
                    List<String> lines = Files.readAllLines(file);
                    for (String line : lines) {
                        if (line.trim().isEmpty()) continue;
                        
                        Clipping clipping = mapper.readValue(line, Clipping.class);
                        
                        // Apply the case-insensitive title filter if one was provided
                        if (titleFilter == null || titleFilter.isBlank() || 
                            (clipping.bookTitle() != null && 
                             clipping.bookTitle().toLowerCase().contains(titleFilter.toLowerCase()))) {
                            clippings.add(clipping);
                        }
                    }
                }
            }
        }
        return clippings;
    }

    /**
     * Deletes the temporary directory and all its contents recursively.
     * Prevents cluttering the system's temporary file storage.
     *
     * @param dir the directory to recursively delete
     */
    private void deleteTempDir(Path dir) {
        if (!Files.exists(dir)) return;
        try {
            Files.walkFileTree(dir, new SimpleFileVisitor<Path>() {
                @Override
                public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                    Files.delete(file);
                    return FileVisitResult.CONTINUE;
                }

                @Override
                public FileVisitResult postVisitDirectory(Path d, IOException exc) throws IOException {
                    Files.delete(d);
                    return FileVisitResult.CONTINUE;
                }
            });
        } catch (IOException ignored) {
            // Ignore cleanup errors for temp dirs
        }
    }
}
