package io.github.vlovric.kindleparser.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A single highlight or note from MyClippings.txt.
 * Mapped to match the JSON output generated by the Fyodor ERB template.
 */
public record Clipping(
    @JsonProperty("book_title") String bookTitle,
    @JsonProperty("author") String author,
    @JsonProperty("type") String type,
    @JsonProperty("loc") Integer location,
    @JsonProperty("page") Integer page,
    @JsonProperty("date") String date,
    @JsonProperty("text") String content
) {
    /**
     * Checks if this clipping represents a highlight.
     *
     * @return true if the clipping is a highlight
     */
    public boolean isHighlight() {
        return type != null && type.equalsIgnoreCase("highlight");
    }

    /**
     * Checks if this clipping represents a note.
     *
     * @return true if the clipping is a note
     */
    public boolean isNote() {
        return type != null && type.equalsIgnoreCase("note");
    }
}
