package io.github.vlovric.kindleparser.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A single highlight or note from MyClippings.txt.
 * Mapped to match the JSON output generated by the Fyodor ERB template.
 * Fyodor output:
 * {"book_title":"","author":"","type":"","loc":"241-242","page":"16","date":"","text":""}
 * Types can be: "highlight", "note", "bookmark", or "clip"
 * Only "highlight", "note" and "bookmark" are supported
 */
public record Clipping(
    @JsonProperty("book_title") String bookTitle,
    @JsonProperty("author") String author,
    @JsonProperty("type") String type,
    @JsonProperty("loc") String rawLocation,
    @JsonProperty("page") Integer page,
    @JsonProperty("date") String date,
    @JsonProperty("text") String content
) {
    /**
     * Extracts the first integer from the raw location string (e.g. "18-22" -> 18).
     *
     * @return the starting location as an Integer, or null if unparseable
     */
    public Integer location() {
        if (rawLocation == null || rawLocation.isBlank() || rawLocation.equals("null")) {
            return null;
        }
        String[] parts = rawLocation.split("-");
        if (parts.length > 0) {
            try {
                return Integer.valueOf(parts[0].trim());
            } catch (NumberFormatException e) {
                // Ignore fallback to null
            }
        }
        return null;
    }

    /**
     * Checks if this clipping represents a highlight.
     *
     * @return true if the clipping is a highlight
     */
    public boolean isHighlight() {
        return type != null && type.equalsIgnoreCase("highlight");
    }

    /**
     * Checks if this clipping represents a note.
     *
     * @return true if the clipping is a note
     */
    public boolean isNote() {
        return type != null && type.equalsIgnoreCase("note");
    }

    /**
     * Checks if this clipping represents a bookmark.
     *
     * @return true if the clipping is a bookmark
     */
    public boolean isBookmark() {
        return type != null && type.equalsIgnoreCase("bookmark");
    }
}
